### PR TITLE
feat: add htmldjango support

### PR DESCRIPTION
**Pull request by whleucka**
Hi there! This is great! Congrats!

I'd like to contribute to this plugin, if that is ok.
I just wanted to add htmldjango support as well (this would work for twig templates as well)

### CODE REVIEW

**Comment by MaximilianLloyd** [comment]
Thank you 😄! I'll have a look at this tonight. I'm thinking maybe adding html as a fallback parser when no defined ones are available would solve it for a lot of languages.

**Comment by MaximilianLloyd** [comment]
I made a new commit setting the HTML parser as the fallback. I nested with htmldjango and twig, does it work for you as well after updating the plugin?

**Comment by whleucka** [comment]
I will pull the new version and get back to you.

**Comment by whleucka** [comment]
image

Looks good!

**Comment by MaximilianLloyd** [comment]
Thank you for you the PR, i'll close it for now since the underlying issue has been solved

**Pull request closed without merging**
