### PR TITLE
modifies treesitter query to match for the class attribute

### PR DESCRIPTION
**Pull request by catgoose**

### CODE REVIEW

**Comment by catgoose** [comment]
Added nil check for parent because plugin would error if you tried to use it on the inner brackets of something like:

```vue
<template>
  <div id="app" class="grid grid-cols-3 bg-white">
    <h1>{{ c }}</h1>
    <button
      @click="store.increment"
      class="py-2 px-4 font-bold text-white bg-blue-500 rounded hover:bg-blue-700"
    >
      Increment
    </button>
    <router-view />
  </div>
</template>
```

Executing `TWValues` with  cursor over the inner { or } of the `h1` tag here will cause error.

**Comment by MaximilianLloyd** [comment]
Hi! Thanks for the contribution. Can you comment with the error message? Also wondering what template language that is?

**Comment by catgoose** [comment]
If I remember correctly it's something about parent being nil. That's why I added the nil check.

That's from a vue template.

**Comment by emilford** [comment]
I get the following error when using the plugin in an ERB template. Looks like it might be the same issue.

```
Error executing Lua callback: ...al/share/nvim/lazy/tw-values.nvim/lua/tw-values/init.lua:43: attempt to index local 'parent' (a nil value) 
stack traceback:
        ...al/share/nvim/lazy/tw-values.nvim/lua/tw-values/init.lua:43: in function 'show'
        ...ocal/share/nvim/lazy/tw-values.nvim/plugin/tw-values.lua:2: in function <...ocal/share/nvim/lazy/tw-values.nvim/plugin/tw-values.lua:1>
```

**Comment by catgoose** [comment]
Any chance you can look at this?

**Pull request merged**
